if not (IsAddOnLoaded("Tukui") or IsAddOnLoaded("AsphyxiaUI") or IsAddOnLoaded("DuffedUI")) then return end
local US = unpack(select(2,...))

local name = "AuctionatorSkin"
function US:SkinAuctionator(event)
	if event == "PLAYER_ENTERING_WORLD" then return end
	AuctionsCancelAuctionButton:Point("RIGHT", AuctionFrameMoneyFrame, "RIGHT", 554, 0)
	AuctionsCloseButton:ClearAllPoints()
	AuctionsCloseButton:Point("RIGHT", AuctionsCancelAuctionButton, "RIGHT", 86, 0)
	BidBuyoutButton:Point("RIGHT", BidCloseButton, "LEFT", -4, 0)
	BidBidButton:Point("RIGHT", BidBuyoutButton, "LEFT", -4, 0)
	BrowseName:Point("TOPLEFT", AuctionFrameBrowse, "TOPLEFT", 22, -56)
	BrowseMinLevel:ClearAllPoints()
	BrowseMinLevel:Point("RIGHT", BrowseName, "RIGHT", 42, 0)
	BrowseMaxLevel:ClearAllPoints()
	BrowseMaxLevel:Point("RIGHT", BrowseMinLevel, "RIGHT", 36, 0)
	BrowseDropDown:ClearAllPoints()
	BrowseDropDown:Point("RIGHT", BrowseMaxLevel, "RIGHT", 150, -3)
	BrowseResetButton:ClearAllPoints()
	BrowseResetButton:Point("LEFT", BrowseName, "LEFT", -2, -26)
	BrowseSearchButton:ClearAllPoints()
	BrowseSearchButton:Point("RIGHT", BrowseResetButton, "RIGHT", 83, 0)
	BrowseResetButton:Width(80)
	BrowseNameText:Point("TOPLEFT", 20, -41)
	BrowseLevelText:Point("TOPLEFT", 184, -45)
	BrowseLevelHyphen:Point("LEFT", BrowseMinLevel, "RIGHT", 4, 0)
	AuctionFrameMoneyFrame:ClearAllPoints()
	AuctionFrameMoneyFrame:Point("TOPLEFT", AuctionFrame, "BOTTOMLEFT", 55, 24)	
	BrowseBidPrice:ClearAllPoints()
	BrowseBidPrice:Point("RIGHT", AuctionFrameMoneyFrame, "RIGHT", 340, 0)
	BrowseCloseButton:ClearAllPoints()
	BrowseCloseButton:Point("RIGHT", AuctionFrameMoneyFrame, "RIGHT", 640, 0)
	BrowseBuyoutButton:Point("RIGHT", BrowseCloseButton, "LEFT", -4, 0)
	BrowseBidButton:Point("RIGHT", BrowseBuyoutButton, "LEFT", -4, 0)
	BidBidPrice:ClearAllPoints()
	BidBidPrice:Point("RIGHT", AuctionFrameMoneyFrame, "RIGHT", 340, 0)
	BidCloseButton:ClearAllPoints()
	BidCloseButton:Point("RIGHT", AuctionFrameMoneyFrame, "RIGHT", 640, 0)
	BidBuyoutButton:Point("RIGHT", BrowseCloseButton, "LEFT", -4, 0)
	BidBidButton:Point("RIGHT", BrowseBuyoutButton, "LEFT", -4, 0)
	AuctionsQualitySort:Point("TOPLEFT", AuctionFrameAuctions, "TOPLEFT", 219, -48)
	BidQualitySort:Point("TOPLEFT", AuctionFrameBid, "TOPLEFT", 65, -50)
	AuctionFrameTab1:ClearAllPoints()
	AuctionFrameTab1:Point("TOPLEFT", AuctionFrame, "BOTTOMLEFT", -5, 2)
	BrowseNextPageButton:Size(20, 20)
	BrowsePrevPageButton:Size(20, 20)

	US:SkinFrame(Atr_BasicOptionsFrame)
	US:SkinFrame(Atr_TooltipsOptionsFrame)
	US:SkinFrame(Atr_UCConfigFrame)
	US:SkinFrame(Atr_StackingOptionsFrame)
	US:SkinFrame(Atr_ScanningOptionsFrame)
	US:SkinFrame(AuctionatorResetsFrame)
	US:SkinFrame(Atr_ShpList_Options_Frame)
	US:SkinFrame(AuctionatorDescriptionFrame)
	US:SkinFrame(Atr_Stacking_List)
	US:SkinFrame(Atr_ShpList_Frame)
	US:SkinCheckBox(AuctionatorOption_Enable_Alt_CB)
	US:SkinCheckBox(AuctionatorOption_Open_All_Bags_CB)
	US:SkinCheckBox(AuctionatorOption_Show_StartingPrice_CB)
	US:SkinCheckBox(ATR_tipsVendorOpt_CB)
	US:SkinCheckBox(ATR_tipsAuctionOpt_CB)
	US:SkinCheckBox(ATR_tipsDisenchantOpt_CB)
	US:SkinDropDownBox(AuctionatorOption_Deftab)
	US:SkinDropDownBox(Atr_tipsShiftDD)
	US:SkinDropDownBox(Atr_deDetailsDD)
	US:SkinDropDownBox(Atr_scanLevelDD)
	Atr_deDetailsDDText:SetJustifyH('RIGHT')

	local moneyEditBoxes = {
		'UC_5000000_MoneyInput',
		'UC_1000000_MoneyInput',
		'UC_200000_MoneyInput',
		'UC_50000_MoneyInput',
		'UC_10000_MoneyInput',
		'UC_2000_MoneyInput',
		'UC_500_MoneyInput',
	}

	for i = 1, #moneyEditBoxes do
		US:SkinEditBox(_G[moneyEditBoxes[i]..'Gold'])
		US:SkinEditBox(_G[moneyEditBoxes[i]..'Silver'])
		US:SkinEditBox(_G[moneyEditBoxes[i]..'Copper'])
	end

	US:SkinEditBox(Atr_Starting_Discount)
	US:SkinEditBox(Atr_ScanOpts_MaxHistAge)
	US:SkinButton(Atr_UCConfigFrame_Reset)
	US:SkinButton(Atr_StackingOptionsFrame_Edit)
	US:SkinButton(Atr_StackingOptionsFrame_New)

	for i = 1, Atr_ShpList_Options_Frame:GetNumChildren() do
		local object = select(i, Atr_ShpList_Options_Frame:GetChildren())
		if object:GetObjectType() == 'Button' then
			US:SkinButton(object)
		end
	end
	for i = 1, AuctionatorResetsFrame:GetNumChildren() do
		local object = select(i, AuctionatorResetsFrame:GetChildren())
		if object:GetObjectType() == 'Button' then
			US:SkinButton(object)
		end
	end

	US:SkinDropDownBox(Atr_Duration)
	US:SkinDropDownBox(Atr_DropDownSL)
	US:SkinDropDownBox(Atr_ASDD_Class)
	US:SkinDropDownBox(Atr_ASDD_Subclass)

	US:SkinButton(Atr_Search_Button, true)
	US:SkinButton(Atr_Back_Button, true)
	US:SkinButton(Atr_Buy1_Button, true)
	US:SkinButton(Atr_Adv_Search_Button, true)
	US:SkinButton(Atr_FullScanButton, true)
	US:SkinButton(Auctionator1Button, true)
	US:SkinFrame(Atr_ListTabsTab1)
	US:SkinFrame(Atr_ListTabsTab2)
	US:SkinFrame(Atr_ListTabsTab3)
	US:SkinButton(Atr_CreateAuctionButton, true)
	US:SkinButton(Atr_RemFromSListButton, true)
	US:SkinButton(Atr_AddToSListButton, true)
	US:SkinButton(Atr_SrchSListButton, true)
	US:SkinButton(Atr_MngSListsButton, true)
	US:SkinButton(Atr_NewSListButton, true)
	US:SkinButton(Atr_CheckActiveButton, true)
	US:SkinButton(AuctionatorCloseButton, true)
	US:SkinButton(Atr_CancelSelectionButton, true)
	US:SkinButton(Atr_FullScanStartButton, true)
	US:SkinButton(Atr_FullScanDone, true)
	US:SkinButton(Atr_CheckActives_Yes_Button, true)
	US:SkinButton(Atr_CheckActives_No_Button, true)
	US:SkinButton(Atr_Adv_Search_ResetBut, true)
	US:SkinButton(Atr_Adv_Search_OKBut, true)
	US:SkinButton(Atr_Adv_Search_CancelBut, true)
	US:SkinButton(Atr_Buy_Confirm_OKBut, true)
	US:SkinButton(Atr_Buy_Confirm_CancelBut, true)
	US:SkinButton(Atr_SaveThisList_Button, true)
	US:SkinEditBox(Atr_StackPriceGold)
	US:SkinEditBox(Atr_StackPriceSilver)
	US:SkinEditBox(Atr_StackPriceCopper)
	US:SkinEditBox(Atr_StartingPriceGold)
	US:SkinEditBox(Atr_StartingPriceSilver)
	US:SkinEditBox(Atr_StartingPriceCopper)
	US:SkinEditBox(Atr_ItemPriceGold)
	US:SkinEditBox(Atr_ItemPriceSilver)
	US:SkinEditBox(Atr_ItemPriceCopper)
	US:SkinEditBox(Atr_Batch_NumAuctions)
	US:SkinEditBox(Atr_Batch_Stacksize)
	US:SkinEditBox(Atr_Search_Box)
	US:SkinEditBox(Atr_AS_Searchtext)
	US:SkinEditBox(Atr_AS_Minlevel)
	US:SkinEditBox(Atr_AS_Maxlevel)
	US:SkinEditBox(Atr_AS_MinItemlevel)
	US:SkinEditBox(Atr_AS_MaxItemlevel)
	US:SkinFrame(Atr_FullScanResults)
	US:SkinFrame(Atr_Adv_Search_Dialog)
	US:SkinFrame(Atr_FullScanFrame)
	US:SkinFrame(Atr_HeadingsBar,"Default")
	Atr_HeadingsBar:Height(19)
	US:SkinFrame(Atr_Error_Frame)
	US:SkinFrame(Atr_Hlist,"Default")
	Atr_Hlist:Width(196)
	Atr_Hlist:ClearAllPoints()
	Atr_Hlist:Point("TOPLEFT", -195, -75)
	US:SkinFrame(Atr_Buy_Confirm_Frame,"Default")
	US:SkinFrame(Atr_CheckActives_Frame,"Default")
	Atr_SrchSListButton:Width(196)
	Atr_MngSListsButton:Width(196)
	Atr_NewSListButton:Width(196)
	Atr_CheckActiveButton:Width(196)
	US:SkinScrollBar(Atr_Hlist_ScrollFrameScrollBar)
	Atr_ListTabs:Point("BOTTOMRIGHT", Atr_HeadingsBar, "TOPRIGHT", 8, 1)
	Atr_Back_Button:Point("TOPLEFT", Atr_HeadingsBar, "TOPLEFT", 0, 19)

	AuctionatorCloseButton:ClearAllPoints()
	AuctionatorCloseButton:Point("BOTTOMLEFT", Atr_Main_Panel, "BOTTOMRIGHT", -17, 10)
	Atr_Buy1_Button:Point("RIGHT", AuctionatorCloseButton, "LEFT", -5, 0)
	Atr_CancelSelectionButton:Point("RIGHT", Atr_Buy1_Button, "LEFT", -5, 0)
	Atr_SellControls_Tex:StripTextures()
	Atr_SellControls_Tex:StyleButton()
	Atr_SellControls_Tex:SetTemplate("Default", true)
	for i = 4, AuctionFrame.numTabs do
		US:SkinTab(_G["AuctionFrameTab"..i])
	end
	AuctionFrameTab1:Point("TOPLEFT", AuctionFrame, "BOTTOMLEFT", 5, 2)
	US:UnregisterEvent(name, self, event)
end

US:RegisterSkin(name, US.SkinAuctionator, 'AUCTION_HOUSE_SHOW')