if not (IsAddOnLoaded("Tukui") or IsAddOnLoaded("AsphyxiaUI") or IsAddOnLoaded("DuffedUI")) then return end
local US = unpack(select(2,...))

local name = "KarniCrapSkin"
function US:SkinKarniCrap()
	US:SkinFrame(KarniCrap)
	US:SkinFrame(KarniCrap_CategoryFrame)
	US:SkinFrame(KarniCrap_OptionsFrame)
	US:SkinFrame(KarniCrap_Blacklist)
	US:SkinFrame(KarniCrap_Whitelist)
	US:SkinFrame(KarniCrap_Inventory)
	KarniCrap_Inventory_ScrollBar:StripTextures(True)
	KarniCrapTab1:Point("BOTTOMLEFT", KarniCrap, "BOTTOMLEFT",0,-30)
	US:SkinScrollBar(KarniCrap_Inventory_ScrollBarScrollBar)
	US:SkinButton(KarniCrap_BtnBlacklistRemove)
	US:SkinButton(KarniCrap_BtnWhitelistRemove)
	US:SkinCloseButton(KarniCrapCloseButton)
	US:SkinTab(KarniCrapTab1)
	US:SkinTab(KarniCrapTab2)
	US:SkinTab(KarniCrapTab3)
	US:SkinButton(KarniCrap_InvHeader1)
	US:SkinButton(KarniCrap_InvHeader2)
	US:SkinButton(KarniCrap_ValueHeader)
	US:SkinButton(KarniCrap_InvHeader4)
	US:SkinButton(KarniCrap_BtnDestroyItem)
	US:SkinButton(KarniCrap_BtnDestroyAllCrap)
	KarniCrapPortrait:Kill()
	US:SkinCheckBox(KarniCrap_CBEnabled)
	US:SkinCheckBox(KarniCrap_CBPoor)
	US:SkinCheckBox(KarniCrap_Tab1_CBCommon)
	US:SkinCheckBox(KarniCrap_Tab1_CBUseStackValue)
	US:SkinCheckBox(KarniCrap_Tab1_CBEcho)
	US:SkinCheckBox(KarniCrap_CBDestroy)
	US:SkinCheckBox(KarniCrap_CBDestroySlots)
	US:SkinCheckBox(KarniCrap_CBNoDestroyTradeskill)
	US:SkinCheckBox(KarniCrap_CBDestroyGroup)
	US:SkinCheckBox(KarniCrap_CBDestroyRaid)
	US:SkinCheckBox(KarniCrap_Cloth_CBLinen)
	US:SkinCheckBox(KarniCrap_Cloth_CBLinen_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBWool)
	US:SkinCheckBox(KarniCrap_Cloth_CBWool_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBSilk)
	US:SkinCheckBox(KarniCrap_Cloth_CBSilk_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBMageweave)
	US:SkinCheckBox(KarniCrap_Cloth_CBMageweave_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBRunecloth)
	US:SkinCheckBox(KarniCrap_Cloth_CBRunecloth_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBNetherweave)
	US:SkinCheckBox(KarniCrap_Cloth_CBNetherweave_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBFrostweave)
	US:SkinCheckBox(KarniCrap_Cloth_CBFrostweave_Never)
	US:SkinCheckBox(KarniCrap_Cloth_CBEmbersilk)
	US:SkinCheckBox(KarniCrap_Cloth_CBEmbersilk_Never)
	US:SkinCheckBox(KarniCrap_Corpses_CBSkinnable)
	US:SkinCheckBox(KarniCrap_Corpses_CBGatherable)
	US:SkinCheckBox(KarniCrap_Corpses_CBMinable)
	US:SkinCheckBox(KarniCrap_Corpses_CBEngineerable)
	US:SkinCheckBox(KarniCrap_Corpses_CBSkilledEnough)
	US:SkinCheckBox(KarniCrap_Consumables_RBFood1)
	US:SkinCheckBox(KarniCrap_Consumables_RBFood2)
	US:SkinCheckBox(KarniCrap_Consumables_CBFoodMax)
	US:SkinCheckBox(KarniCrap_Consumables_RBWater1)
	US:SkinCheckBox(KarniCrap_Consumables_RBWater2)
	US:SkinCheckBox(KarniCrap_Consumables_CBWaterMax)
	US:SkinCheckBox(KarniCrap_Potions_RBHealth1)
	US:SkinCheckBox(KarniCrap_Potions_RBHealth2)
	US:SkinCheckBox(KarniCrap_Potions_CBHealthMax)
	US:SkinCheckBox(KarniCrap_Potions_RBMana1)
	US:SkinCheckBox(KarniCrap_Potions_RBMana2)
	US:SkinCheckBox(KarniCrap_Potions_CBManaMax)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityPoor)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityCommon)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityUncommon)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityRare)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityEpic)
	US:SkinCheckBox(KarniCrap_Quality_CBQualityGrouped)
	US:SkinCheckBox(KarniCrap_Scrolls_CBMaxScrolls)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollAgility)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollIntellect)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollProtection)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollSpirit)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollStamina)
	US:SkinCheckBox(KarniCrap_Scrolls_CBScrollStrength)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBCooking)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBFishing)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBPickpocketing)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBEnchanting)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBGathering)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBMilling)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBMining)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBProspecting)
	US:SkinCheckBox(KarniCrap_Tradeskills_CBSkinning)
	US:SkinCheckBox(KarniCrap_Inventory_CBHideQuestItems)
	US:SkinCheckBox(KarniCrap_CBOpenAtMerchant)

	for i = 1, 15 do
		US:SkinCloseButton(_G["KarniInvEntry"..i.."_BtnCrap"])
	end

--	US:SkinEditBox(KarniCrap_Poor_GoldInputBox)	
--	US:SkinEditBox(KarniCrap_Poor_SilverInputBox)
--	US:SkinEditBox(KarniCrap_Poor_CopperInputBox)
--	US:SkinEditBox(KarniCrap_Tab1_CBCommonDesc_GoldInputBox)
--	US:SkinEditBox(KarniCrap_Tab1_CBCommonDesc_SilverInputBox)
--	US:SkinEditBox(KarniCrap_Tab1_CBCommonDesc_CopperInputBox)
--	US:SkinEditBox(KarniCrap_EBDestroySlotsNum)
end

US:RegisterSkin(name, US.SkinKarniCrap)