if not (IsAddOnLoaded("Tukui") or IsAddOnLoaded("AsphyxiaUI") or IsAddOnLoaded("DuffedUI")) then return end
local US = unpack(select(2,...))

local name = "OutfitterSkin"
function US:SkinOutfitter()
	CharacterFrame:HookScript("OnShow", function(self) PaperDollSidebarTabs:SetPoint("BOTTOMRIGHT", CharacterFrameInsetRight, "TOPRIGHT", -14, 0) end)
	OutfitterFrame:HookScript("OnShow", function(self) 
		US:SkinFrame(OutfitterFrame)
		OutfitterFrameTab1:Size(60, 25)
		OutfitterFrameTab2:Size(60, 25)
		OutfitterFrameTab3:Size(60, 25)
		OutfitterMainFrame:StripTextures(true)
		for i = 0, 13 do
			if _G["OutfitterItem"..i.."OutfitSelected"] then 
				US:SkinButton(_G["OutfitterItem"..i.."OutfitSelected"])
				_G["OutfitterItem"..i.."OutfitSelected"]:ClearAllPoints()
				_G["OutfitterItem"..i.."OutfitSelected"]:Size(16)
				_G["OutfitterItem"..i.."OutfitSelected"]:Point("LEFT", _G["OutfitterItem"..i.."Outfit"], "LEFT", 8, 0)
			end
		end
	end)

	OutfitterMainFrameScrollbarTrench:StripTextures(true)
	OutfitterFrameTab1:ClearAllPoints()
	OutfitterFrameTab2:ClearAllPoints()
	OutfitterFrameTab3:ClearAllPoints()
	OutfitterFrameTab1:Point("TOPLEFT", OutfitterFrame, "BOTTOMRIGHT", -65, -2)
	OutfitterFrameTab2:Point("LEFT", OutfitterFrameTab1, "LEFT", -65, 0)
	OutfitterFrameTab3:Point("LEFT", OutfitterFrameTab2, "LEFT", -65, 0)
	US:SkinButton(OutfitterFrameTab1, true)
	US:SkinButton(OutfitterFrameTab2, true)
	US:SkinButton(OutfitterFrameTab3, true)
	US:SkinScrollBar(OutfitterMainFrameScrollFrameScrollBar)
	US:SkinCloseButton(OutfitterCloseButton)
	US:SkinButton(OutfitterNewButton)
	US:SkinButton(OutfitterEnableNone)
	US:SkinButton(OutfitterEnableAll)
	US:Desaturate(OutfitterButton)
	OutfitterButton:ClearAllPoints()
	OutfitterButton:SetPoint("RIGHT", PaperDollSidebarTabs, "RIGHT", 26, -2)
	OutfitterButton:SetHighlightTexture(nil)
	OutfitterSlotEnables:SetFrameStrata("HIGH")
	US:SkinCheckBox(OutfitterEnableHeadSlot)
	US:SkinCheckBox(OutfitterEnableNeckSlot)
	US:SkinCheckBox(OutfitterEnableShoulderSlot)
	US:SkinCheckBox(OutfitterEnableBackSlot)
	US:SkinCheckBox(OutfitterEnableChestSlot)
	US:SkinCheckBox(OutfitterEnableShirtSlot)
	US:SkinCheckBox(OutfitterEnableTabardSlot)
	US:SkinCheckBox(OutfitterEnableWristSlot)
	US:SkinCheckBox(OutfitterEnableMainHandSlot)
	US:SkinCheckBox(OutfitterEnableSecondaryHandSlot)
	US:SkinCheckBox(OutfitterEnableHandsSlot)
	US:SkinCheckBox(OutfitterEnableWaistSlot)
	US:SkinCheckBox(OutfitterEnableLegsSlot)
	US:SkinCheckBox(OutfitterEnableFeetSlot)
	US:SkinCheckBox(OutfitterEnableFinger0Slot)
	US:SkinCheckBox(OutfitterEnableFinger1Slot)
	US:SkinCheckBox(OutfitterEnableTrinket0Slot)
	US:SkinCheckBox(OutfitterEnableTrinket1Slot)
	US:SkinButton(OutfitterItemComparisons)
	US:SkinButton(OutfitterTooltipInfo)
	US:SkinButton(OutfitterShowHotkeyMessages)
	US:SkinButton(OutfitterShowMinimapButton)
	US:SkinButton(OutfitterShowOutfitBar)
	US:SkinButton(OutfitterAutoSwitch)
	OutfitterItemComparisons:Size(20)
	OutfitterTooltipInfo:Size(20)
	OutfitterShowHotkeyMessages:Size(20)
	OutfitterShowMinimapButton:Size(20)
	OutfitterShowOutfitBar:Size(20)
	OutfitterAutoSwitch:Size(20)
	OutfitterShowOutfitBar:Point("TOPLEFT", OutfitterAutoSwitch, "BOTTOMLEFT", 0, -5)
	US:SkinButton(OutfitterEditScriptDialogDoneButton)
	US:SkinButton(OutfitterEditScriptDialogCancelButton)
	US:SkinScrollBar(OutfitterEditScriptDialogSourceScriptScrollBar)
	US:SkinBackdropFrame(OutfitterEditScriptDialogSourceScript)
	US:SkinFrame(OutfitterEditScriptDialog)
	US:SkinCloseButton(OutfitterEditScriptDialog.CloseButton)
	US:SkinTab(OutfitterEditScriptDialogTab1)
	US:SkinTab(OutfitterEditScriptDialogTab2)
end

US:RegisterSkin(name, US.SkinOutfitter)