if not (IsAddOnLoaded("Tukui") or IsAddOnLoaded("AsphyxiaUI") or IsAddOnLoaded("DuffedUI")) then return end
local US = unpack(select(2,...))

local name = "PoisonerSkin"
function US:SkinPoisoner()
	US:SkinFrame(PoisonerOptions_SettingsFrame)
	US:SkinButton(PoisonerOptions_MenuSortingButton)
	US:SkinButton(PoisonerOptions_SettingsSave)
	US:SkinButton(PoisonerOptions_SettingsClose)
	US:SkinButton(PoisonerOptions_ResetFBPosition)
	US:SkinCheckBox(PoisonerOptions_ChkBox_Enable)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MBShow)
	US:SkinCheckBox(PoisonerOptions_ChkBox_FBShow)
	US:SkinCheckBox(PoisonerOptions_ChkBox_FBLock)
	US:SkinCheckBox(PoisonerOptions_ChkBox_PoisonWeaponChatOuput)
	US:SkinCheckBox(PoisonerOptions_ChkBox_ShowOnMouseover)
	US:SkinCheckBox(PoisonerOptions_ChkBox_AutoHide_inCombat)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MenuParentOwn)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MenuParentMinimap)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPTopLeft)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPTop)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPTopRight)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPLeft)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPRight)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPBottomLeft)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPBottom)
	US:SkinCheckBox(PoisonerOptions_ChkBox_MPBottomRight)
	US:SkinCheckBox(PoisonerOptions_ChkBox_ToolTipFull)
	US:SkinCheckBox(PoisonerOptions_ChkBox_ToolTipName)
	US:SkinCheckBox(PoisonerOptions_ChkBox_OverwritePreset)
	US:SkinCheckBox(PoisonerOptions_ChkBox_ShowTimer)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_IgnoreWhileFishing)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_OnlyInstanced)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_MainHand)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_OffHand)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_ThrowWeapon)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_Audio)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_Chat)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_Aura)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_ErrorFrame)
	US:SkinCheckBox(PoisonerOptions_ChkBox_TimerOutput_Aura_Lock)
	US:SkinCheckBox(PoisonerOptions_ChkBox_AutoBuy)
	US:SkinCheckBox(PoisonerOptions_ChkBox_AutoBuy_Prompt)
	US:SkinCheckBox(PoisonerOptions_ChkBox_AutoBuy_Check)
	US:SkinCheckBox(PoisonerOptions_ChkBox_QuickButton_Lock)

	PoisonerOptions_SettingsFrameTab1:Point("TOPLEFT", PoisonerOptions_SettingsFrame, "BOTTOMLEFT", 0, 2)

	for i = 1, 5 do
		US:SkinTab(_G["PoisonerOptions_SettingsFrameTab"..i])
	end
end

US:RegisterSkin(name, US.SkinPoisoner)