if not (IsAddOnLoaded("Tukui") or IsAddOnLoaded("AsphyxiaUI") or IsAddOnLoaded("DuffedUI")) then return end
local US = unpack(select(2,...))

local name = "TradeSkillDWSkin"
function US:SkinTradeSkillDW()
	US:SkinFrame(TradeSkillFrame)
	TradeSkillListScrollFrame:StripTextures(True)
	TradeSkillDetailScrollFrame:StripTextures(True)
	TradeSkillFrameInset:StripTextures(True)
	TradeSkillExpandButtonFrame:StripTextures(True)
	TradeSkillDetailScrollChildFrame:StripTextures(True)
	TradeSkillListScrollFrame:StripTextures(True)
	US:SkinFrame(TradeSkillGuildFrame)
	US:SkinFrame(TradeSkillGuildFrameContainer)
	TradeSkillGuildFrame:Point("BOTTOMLEFT", TradeSkillFrame, "BOTTOMRIGHT", 3, 19)
	US:SkinCloseButton(TradeSkillGuildFrameCloseButton)
	TradeSkillFrame:HookScript("OnShow", function() US:SkinFrame(TradeSkillFrame) TradeSkillListScrollFrame:StripTextures() if not TradeSkillDWExpandButton then return end if not TradeSkillDWExpandButton.skinned then US:SkinNextPrevButton(TradeSkillDWExpandButton) TradeSkillDWExpandButton.skinned = true end end)
	TradeSkillFrame:Height(TradeSkillFrame:GetHeight() + 12)
	US:SkinStatusBar(TradeSkillRankFrame)
	US:SkinButton(TradeSkillCreateButton, true)
	US:SkinButton(TradeSkillCancelButton, true)
	US:SkinButton(TradeSkillFilterButton, true)
	US:SkinButton(TradeSkillCreateAllButton, true)
	US:SkinButton(TradeSkillViewGuildCraftersButton, true)
	TradeSkillLinkButton:GetNormalTexture():SetTexCoord(0.25, 0.7, 0.37, 0.75)
	TradeSkillLinkButton:GetPushedTexture():SetTexCoord(0.25, 0.7, 0.45, 0.8)
	TradeSkillLinkButton:GetHighlightTexture():Kill()
	US:SkinBackdropFrame(TradeSkillLinkButton)
	TradeSkillLinkButton:Size(17, 14)
	TradeSkillLinkButton:Point("LEFT", TradeSkillLinkFrame, "LEFT", 5, -1)
	US:SkinEditBox(TradeSkillFrameSearchBox)
	US:SkinEditBox(TradeSkillInputBox)
	--US:SkinNextPrevButton(TradeSkillDecrementButton)
	--US:SkinNextPrevButton(TradeSkillIncrementButton)
	TradeSkillIncrementButton:Point("RIGHT", TradeSkillCreateButton, "LEFT", -13, 0)
	US:SkinCloseButton(TradeSkillFrameCloseButton)
	US:SkinScrollBar(TradeSkillDetailScrollFrameScrollBar)
	--US:SkinScrollBar(TradeSkillListScrollFrameScrollBar)
	local once = false
	hooksecurefunc("TradeSkillFrame_SetSelection", function(id)
		TradeSkillSkillIcon:StyleButton()
		if TradeSkillSkillIcon:GetNormalTexture() then
			TradeSkillSkillIcon:GetNormalTexture():SetTexCoord(.08, .92, .08, .92)
			TradeSkillSkillIcon:GetNormalTexture():ClearAllPoints()
			TradeSkillSkillIcon:GetNormalTexture():Point("TOPLEFT", 2, -2)
			TradeSkillSkillIcon:GetNormalTexture():Point("BOTTOMRIGHT", -2, 2)
		end
		TradeSkillSkillIcon:SetTemplate("Default")
		for i = 1, MAX_TRADE_SKILL_REAGENTS do
			local button = _G["TradeSkillReagent"..i]
			local icon = _G["TradeSkillReagent"..i.."IconTexture"]
			local count = _G["TradeSkillReagent"..i.."Count"]
			icon:SetTexCoord(.08, .92, .08, .92)
			icon:SetDrawLayer("OVERLAY")
			if not icon.Backdrop then
				icon.Backdrop = CreateFrame("Frame", nil, button)
				icon.Backdrop:SetFrameLevel(button:GetFrameLevel() - 1)
				US:SkinFrame(icon.Backdrop)
				icon.Backdrop:Point("TOPLEFT", icon, "TOPLEFT", -2, 2)
				icon.Backdrop:Point("BOTTOMRIGHT", icon, "BOTTOMRIGHT", 2, -2)
			end
			icon:SetParent(icon.Backdrop)
			count:SetParent(icon.Backdrop)
			count:SetDrawLayer("OVERLAY")
			if i > 2 and once == false then
				local point, anchoredto, point2, x, y = button:GetPoint()
				button:ClearAllPoints()
				button:Point(point, anchoredto, point2, x, y - 3)
				once = true
			end
			_G["TradeSkillReagent"..i.."NameFrame"]:Kill()
		end
	end)
	TradeSkillDW_QueueFrame:HookScript("OnShow", function() US:SkinFrame(TradeSkillDW_QueueFrame) end)
	US:SkinCloseButton(TradeSkillDW_QueueFrameCloseButton)
	TradeSkillDW_QueueFrameInset:StripTextures()
	US:SkinButton(TradeSkillDW_QueueFrameClear, true)
	US:SkinButton(TradeSkillDW_QueueFrameDown, true)
	US:SkinButton(TradeSkillDW_QueueFrameUp, true)
	US:SkinButton(TradeSkillDW_QueueFrameDo, true)
	TradeSkillDW_QueueFrameDetailScrollFrame:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrame:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent1:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent2:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent3:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent4:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent5:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent6:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent7:StripTextures()
	TradeSkillDW_QueueFrameDetailScrollFrameChildFrameReagent8:StripTextures()
	US:SkinScrollBar(TradeSkillDW_QueueFrameDetailScrollFrameScrollBar)
	TradeSkillListScrollFrame:StripTextures()
end

US:RegisterSkin(name, US.SkinTradeSkillDW)